;; This file is the main entry point of the Neovim API interface.
;; It rely on generated files src/nvim-*
(module nvim (neovim
              make-neovim
              neovim?
              neovim-client
              connect
              nvim-error->string
              )
  (import scheme
          chicken.base
          chicken.module)
  (import srfi-69
          (prefix msgpack mp:)
          (prefix msgpack-rpc-client mrpc:))

  (define (true . args) #t)

  (define-record-type neovim
    (make-neovim mrpc-client)
    neovim?
    (mrpc-client neovim-client))

  (define (neovim-nvim obj)
    (assert (neovim? obj))
    obj)

  ;; create a connection to an nvim instance
  ;; return a neovim object
  (define (connect mode . args)
    (let ((client (apply mrpc:make-client (cons mode args))))
      (mrpc:connect! client)
      (make-neovim client)))

  (define (nvim-error->string error-type->error-name err)
    (let ((type (vector-ref err 0))
          (msg (vector-ref err 1)))
      (string-append (error-type->error-name type) ": " msg)))

  (define (make-nvim-error type msg)
    (vector type msg))

  ; Those files are generated by code-gen/api-gen.scm
  (include "src/nvim-type-binding.scm")
  (include "src/nvim-function-binding.scm"))
